### PR TITLE
Add Quill.js v0.20.0

### PR DESCRIPTION
**Pull request by exload**

### CODE REVIEW

**Comment by martinklepsch** [comment]
@exload nice one! :+1:

**Comment by martinklepsch** [comment]
@exload I added a `-0` to the version so we can ship fixes of the same quill version.

Thanks for you contribution! :clap:

**Comment by exload** [comment]
You're welcome :smiley:

**Comment by martinklepsch** [comment]
on clojars as `[cljsjs/quill "0.20.0-0"]` FYI :)

**Pull request closed without merging**
