### PR TITLE
[jquery-daterange-picker] Update version

### PR DESCRIPTION
**Pull request by ayazmaroof**
Version 0.0.9 includes bug fixes and enhancements
Also updated moment and jQuery version

Some of the bug fixes:
- Auto close
- Range highlighter

https://github.com/longbill/jquery-date-range-picker/releases

### CODE REVIEW

**Comment by Deraen** [comment]
Hmm, interesting that this package includes the sources instead of downloading them. Anyway, I'll merge this and do another release soon which refactors the packaging task for this lib.

**Comment by Deraen** [comment]
@ayazmaroof Hmm, upstream doesn't have 0.0.9 release so what version is this?

**Comment by Deraen** [comment]
In addition to this `0.0.9-0` there is also now version `0.0.8-0` deployed which downloads the files from upstream. It also removes minified JS code as one is not provided upstream and the code can't be easily minified with asset-minifier.

**Comment by ayazmaroof** [comment]
@Deraen I noticed the 0.0.8 release after I submitted the pull request. The 0.0.9 source code was available in the master of upstream. 
Thanks for updating and downloading the files from upstream.

**Pull request merged**
