### PR TITLE
Highcharts - upgrade to 2.4.5 and removed jquery

### PR DESCRIPTION
**Pull request by yatesco**

### CODE REVIEW

**Comment by yatesco** [comment]
Fixes https://github.com/cljsjs/packages/issues/510 and https://github.com/cljsjs/packages/issues/585

**Comment by Deraen** [comment]
Did you try generating new externs? One note in the change log looks like it might change the API:

- Added new constructor, Highcharts.chart, that allows instanciating a chart without the new keyword.

**Comment by yatesco** [comment]
I'm new to this and boot so I might be mistaken, but target/common/highcharts.ext.js contains:
```
var Highcharts = {
...
  "Chart": function () {},
  "chart": function () {},
...
}
```

which  I think is sufficient, but no, I didn't manually edit that.

**Comment by Deraen** [comment]
Yeah, that looks sufficient.

P.S. I added a few notes about updating packages to wiki: https://github.com/cljsjs/packages/wiki/Updating-packages

**Comment by yatesco** [comment]
Great - thanks!

**Pull request merged**
