### PR TITLE
Introducing bitauth

### LINKED ISSUE #161: Request: Support for BitAuth
It would be awesome if cljsjs had a client-side bitauth package

### PR DESCRIPTION
**Pull request by xcthulhu**
Closes #161

### CODE REVIEW

**Comment by xcthulhu** [comment]
Okay all my tests pass when I use this in my upstream project: https://github.com/xcthulhu/clj-bitauth

My tests run in both JVM Clojure and ClojureScript, so this thing is pretty solid 😁

**Comment by crisptrutski** [comment]
@xcthulhu welcome back :smile: 

A few notes:

1. CLJSJS packages add an extra build-number parameter to the version, so that we can iterate on wrappings for a given underlying lib version.

  I'll take care of adding this when merging, but just wanted to bring it to your attention.

2. Shelling out to `npm` is not something I've seen before here, and while I don't think it's a deal breaker (let @martinklepsch speak to that), we could put a sweater back on the yak by getting the upstream author to include the two built files in the github releases. Looking [back in time](https://github.com/bitpay/bitauth/releases) he used to publish the minified file. 

  Or perhaps he's updating a CDN, and that could also be fine.

  Again no changes required on your side, just floating the suggestions for future updates.

3. Your *iso-mogriphied* `clj-bitauth` repo doesn't actually seem to be using this yet, and also has `js/BitAuth` instead of the `js/bitauth` that this package exposes - I guess that's on an unpublished branch?

  Ran a few of my own tests straight against this and looks good, just mentioning again in case you meant to push or need to mirror that case change.

Going ahead and pulling this in, thanks a lot! :closed_lock_with_key::tropical_drink::v:

**Comment by crisptrutski** [comment]
Merged in 8a58c82aea61a5e1f663db391bf06260cf20aa8b

**Comment by xcthulhu** [comment]
Hey!  So I am using cljsjs/bitauth in clj-bitauth as of version 0.0.3 😋

I am probably going to fork bitpay/bitauth tbh, since the maintainer @martindale is no longer at the company.

For one, the upstream version can't handle unicode (see [stackoverflow](http://stackoverflow.com/q/19354455) for a general discussion on a workaround).

If I fork it, I promise I will put browsified versions in my releases to avoid the npm clumsiness.  Thanks for pulling this in so quickly.

**Pull request closed without merging**
