### PR TITLE
stripe vendor lib

### PR DESCRIPTION
**Pull request by rwillig**
ext only vendor lib for stripejs

### CODE REVIEW

**Comment by martinklepsch** [comment]
@pandeiro @rwillig did you figure out what to do with this yesterday?

**Comment by pandeiro** [comment]
@martinklepsch Almost -- for me the only issue would be a squash into one commit, to keep our history clean... @rwillig could you do that?

**Comment by martinklepsch** [comment]
Ok, great! @rwillig If you do that please prefix with `[stripe]`. :+1:

**Comment by rwillig** [comment]
@pandeiro @martinklepsch do you mean rebase? I'm not exactly sure how to do that but I will look into it.

**Comment by Deraen** [comment]
Something like `git rebase -i HEAD~4` should do. Then select squash for three of the last commits to squash them into the first.

**Comment by rwillig** [comment]
see #74 you can just close this one

**Pull request closed without merging**
