### PR TITLE
[syn] Add syn

### PR DESCRIPTION
**Pull request by retro**
Adds [syn](http://github.com/bitovi/syn) - Standalone Synthetic Event Library

### CODE REVIEW

**Comment by Deraen** [comment]
As you are using `deps-cljs` task you should not also have `deps.cljs` file, as it will be overwritten by the task.

Or do I miss something?

**Comment by retro** [comment]
@Deraen Ok, is it a better practice to remove the `deps-cljs` task or the `deps.cljs` file?

**Comment by Deraen** [comment]
To remove `deps.cljs` and use the task.

**Comment by retro** [comment]
`deps.cljs` file is removed

**Pull request merged**
