### PR TITLE
virtual-dom 2.1.1

### PR DESCRIPTION
**Pull request by crisptrutski**
This combines the best of #186 and #165

@martinklepsch @exupero @Szczyp

### CODE REVIEW

**Comment by crisptrutski** [comment]
@martinklepsch any remaining objections?

**Comment by Szczyp** [comment]
looks good, ty

**Comment by crisptrutski** [comment]
we can always amend, have merged and published `virtual-dom-2.1.1-0`

**Comment by martinklepsch** [comment]
Sorry - all good! 👍

**Pull request merged**
