### PR TITLE
Add missing externs for innerTickSize() and outerTickSize().

### PR DESCRIPTION
**Pull request by jszakmeister**
Bump the package release number to make this ready for release.

### CODE REVIEW

**Comment by jszakmeister** [comment]
FWIW, I did run build this locally, and it resolved my issue with `innerTickSize()` and `outerTickSize()` being renamed.

It looks like the CircleCI build is broken for other reasons.  My best guess is that the gpg.conf needs to be updated to include `batch\n` in it.  If you scroll down in the [GPG Esoteric Options](https://www.gnupg.org/documentation/manuals/gnupg/GPG-Esoteric-Options.html) section to `--passphrase`, you can see it has a note saying:

> Note that this passphrase is only used if the option --batch has also been given. This is different from GnuPG version 1.x.

**Comment by jszakmeister** [comment]
I tried adding batch, but that didn't help.

**Comment by Deraen** [comment]
CI build is broken because it's waiting for new Boot release.

**Comment by Deraen** [comment]
Deployed

**Comment by jszakmeister** [comment]
> CI build is broken because it's waiting for new Boot release.

I managed to see the issue about an hour ago.  Thanks for the info!

> Deployed

Thanks for the quick turn-around!

**Pull request merged**
