### PR TITLE
add twitter's typeahead bundle

### PR DESCRIPTION
**Pull request by flyingmachine**
Externs for https://github.com/twitter/typeahead.js

### CODE REVIEW

**Comment by martinklepsch** [comment]
Merged: https://github.com/cljsjs/packages/commit/016b0c986519372aeed0b19371c73b173d860acf

Nice to have you here @flyingmachine! :)
I added a `cljsjs-version` modifier for the version but merged as is otherwise. :rocket:

**Comment by martinklepsch** [comment]
err, made a mistake

**Comment by martinklepsch** [comment]
Pushed `0.11.1-1` — somehow the externs got lost during the initial merge.
That's what we have those increments for :)

Thanks again

https://github.com/cljsjs/packages/commit/5c061d62a57d63f5c21bc36703e5f8656267f6d2

**Comment by flyingmachine** [comment]
woot! :smile:

**Pull request closed without merging**
