### PR TITLE
Add PIXI.js 3.0.7

### PR DESCRIPTION
**Pull request by jmmk**

### CODE REVIEW

**Comment by jmmk** [comment]
Might be an issue with the minified version. Looking into it.

**Comment by martinklepsch** [comment]
Pom URL needs to be http://pixijs.com I think. Thanks for your effort, I'll take a more in-depth look soon.

**Comment by jmmk** [comment]
Whoops - realized on closer inspection that my extern is incomplete. Haven't had much time to mess around with it, but hopefully with some playing around I can generate a good one.

**Comment by jmmk** [comment]
I'm back from a two-week hiatus and actively working on this. Whether manually or automatically, I hope to be able to get this working soon.

@martinklepsch what's the reasoning for not having "www" in the POM URL?

**Comment by martinklepsch** [comment]
huh, I thought it didn't work with `www` but now it does. Probably my fault :)

**Comment by jmmk** [comment]
Well I had it as www.pixijs.org, which either never existed (in which case I have no idea how or why I entered it), or no longer exists, so I just updated it to www.pixijs.com.

**Comment by jmmk** [comment]
Added the (hopefully) complete externs. I tested them with my project locally and everything seemed good, but I don't know if there's a better way to test.

I wrote an externs generator based on https://github.com/wiseman/closure-externs-generator to do it automatically, so hopefully it can be useful for other projects as well.

**Comment by jmmk** [comment]
@martinklepsch Anything else missing or that needs improvement?

**Comment by dparis** [comment]
@jmmk Don't know how I missed it earlier, just now seeing your PR. :smile:  I submitted a package for Phaser, an HTML5 game engine built on top of PIXI, and wound up using your externs generator:  #175 

I had gotten about half way into writing my tool to generate externs for phaser when I found your generator. Some initial sanity checking showed that it was generating externs very similar to what my tool was partially able to output.

Thanks for saving us all some work!

**Comment by martinklepsch** [comment]
@jmmk @dparis would be awesome if you could add a link to the repo to relevant sections In the wiki so people can find it more easily 👍

**Comment by martinklepsch** [comment]
Will take a look at both PRs today, sorry for taking so long!

**Comment by martinklepsch** [comment]
Merged and deployed to Clojars: https://github.com/cljsjs/packages/commit/531d66735e8f67f0ef3deae8d55f9f982328d608

Thanks a lot to both of you! :rocket: :+1:

**Pull request closed without merging**
