### PR TITLE
[tfjs] Add tfjs 0.11.5

### PR DESCRIPTION
**Pull request by namenu**
TensorFlow.js is A WebGL accelerated JavaScript library for training and deploying ML models.

### CODE REVIEW

**Comment by Deraen** [comment]
This looks like extern-only package? Was this the intention?

**Comment by namenu** [comment]
Yes, I intended since it's still under 1.0.0.
I wasn't sure if I should upload empty checksum file.

**Comment by Deraen** [comment]
Umm, how does the version affect this? How is the JS for TensorFlow.js added to the browser?

**Comment by namenu** [comment]
It is added by `<script>` tag with version number.
e.g.) https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.6
(In the meantime, anew version has been released)

I am thinking that it has not enough reasons to be extern-only, so I have added `download` process.

Please take a look !

**Comment by Deraen** [comment]
Now that `deps-cljs` task is used, the `deps.cljs` file is unncessary. It will be rewritten by the task.

**Pull request merged**
