### PR TITLE
[smoothscroll-polyfill] Update to 0.4.0 (latest).

### PR DESCRIPTION
**Pull request by briantrice**
Update:
**Extern:** I updated the extern by hand.

### CODE REVIEW

**Comment by Deraen** [comment]
Hmm, no need for extern file in this case, as code from this JS file is never called directly?

You can add `:no-externs true` option to `deps-cljs` to skip the check.

**Comment by briantrice** [comment]
You can call the polyfill explicitly for some cases. I'm ambivalent about whether to expose it.

**Comment by briantrice** [comment]
I should say that I want to force the polyfill in Chrome when its version of scrolling doesn't match what's requested. I may do that with the polyfill call since trying to set a flag before "require"ing it in Clojurescript is difficult.

**Comment by Deraen** [comment]
Okay, I don't fully understand how this polyfill works, but if this works for you, this is fine.

**Pull request merged**
