### PR TITLE
Update OL3 to v3.2.0 and fix a bug

### PR DESCRIPTION
**Pull request by olivergeorge**
Two changes included...

* Update to new release of openlayers (v3.2.0)
* Fixes issue with missing ol.ext.rbush

### CODE REVIEW

**Comment by martinklepsch** [comment]
could it be that your branch is not rebased against current master?
There are many commits in here that are already in master.

**Comment by olivergeorge** [comment]
I'll try again

**Comment by martinklepsch** [comment]
@olivergeorge probably easiest to do a new branch from freshly pulled master and cherry pick that one commit:  `e5ea092`.

**Comment by olivergeorge** [comment]
Done.

**Comment by martinklepsch** [comment]
Closing in favor of #39

**Pull request closed without merging**
