### PR TITLE
add iconv-lite

### PR DESCRIPTION
**Pull request by bolasblack**
Keep relevant lines. You should select one choice for each category
(e.g. **Extern**), if none of choices is valid you should probably do
something or at least add a comment here.

New package:

**Extern:** Written by hand.

### CODE REVIEW

**Comment by Deraen** [comment]
What is the yarn.lock file? Does it have to be included in the git?

**Comment by bolasblack** [comment]
@Deraen yarn.lock is generated by [yarn](http://yarnpkg.com/) (a replacement of npm), like Gemfile.lock for bundle. If you npm is enough, we can remove yarn.lock and change the command `yarn` to `npm` in `build.boot`

**Comment by Deraen** [comment]
npm is enough for all other packages so I think it is enough for this. I prefer to keep the packages as similar as possible.

In this case I doubt that npm vs. yarn makes much difference, as iconv-lite itself doesn't have any dependencies, so only thing that might change is transitive dependencies of browserify and uglifyjs.

**Comment by bolasblack** [comment]
@Deraen yarn.lock has deleted now :)

**Comment by bolasblack** [comment]
🍻

**Pull request merged**
