### PR TITLE
Update build.boot

### PR DESCRIPTION
**Pull request by ghostandthemachine**
Bump version and checksum for new version

Update:

**Extern:** The API did not change.

### CODE REVIEW

**Comment by Deraen** [comment]
This package should have dependency and foreign library dependency on React and React-DOM: https://github.com/cljsjs/packages/wiki/Foreign-library-dependencies

**Comment by ghostandthemachine** [comment]
Thanks for the feedback. Should be good to go now.

**Comment by Deraen** [comment]
Looks like the latest commit accidentally reverted the version change.

**Comment by Deraen** [comment]
^ ping @ghostandthemachine

**Pull request closed without merging**
