### PR TITLE
[material] upgrade to mdl 1.2.0

### PR DESCRIPTION
**Pull request by sonwh98**
upgrade to mdl 1.2.0

### CODE REVIEW

**Comment by martinklepsch** [comment]
Hey @sonwh98 👋  Have you checked if the externs need updating? The [release page](https://github.com/google/material-design-lite/releases) mentions a new type of component but I'm not sure if that necessarily means that the API has changed as well.

**Comment by sonwh98** [comment]
Hi @martinklepsch I tested locally using the new components  without any problems

**Comment by Deraen** [comment]
Did you test with `:optimizations :advanced`?

**Comment by flyboarder** [comment]
@Deraen @sonwh98 I checked the commit which introduced the new component and no javascript was included for it to function.

**Comment by sonwh98** [comment]
yes I have tried with advance optimization. However as @flyboarder  says no javascript needed for the new component

**Pull request merged**
