### PR TITLE
Adding codemirror 5.1.0 cljsjs package

### PR DESCRIPTION
**Pull request by jmatsushita**
Hi there,

This works for me, hopefully it'll be useful for others!

Jun

### CODE REVIEW

**Comment by jmatsushita** [comment]
FYI, this doesn't have modes yet.

**Comment by martinklepsch** [comment]
@jmatsushita thanks, this looks really good! You also committed the js and css files which shouldn't be required as those are fetched during `boot package`. If you can remove those that would make it perfect!  :+1:

**Comment by jmatsushita** [comment]
Hi @martinklepsch, thanks for the input! I got the modes in as well, so now it's doing something useful :)

**Comment by martinklepsch** [comment]
@jmatsushita wow, this turned into a truly amazing PR! :star2: 

I wonder if we should minify the files for the separate modes? Any opinions? /ping @Deraen

**Comment by martinklepsch** [comment]
@jmatsushita It's too good to keep it back. I just pushed it to Clojars and merged your changes! Thanks a ton!

**Pull request closed without merging**
