### PR TITLE
Added moment-range.js - Range extenstion for momentjs

### PR DESCRIPTION
**Pull request by chadhq**
Hello,

I've added moment-range 

https://github.com/gf3/moment-range
http://gf3.github.io/moment-range/

It is a plugin extension for the already existing moment(js) library.

Thanks for considering! Let me know if I've forgotten to do anything...

### CODE REVIEW

**Comment by Deraen** [comment]
I presume moment-range depends on Moment. So `cljsjs/moment` should be listed as dependency of this package and `cljsjs.moment` added to `deps.cljs` `:requires` (something like `(deps-cljs :name "cljsjs.moment-range" :requires #{"cljsjs.moment"})` should do it).

Also, remove the commented out stuff from `build.boot`.

**Comment by chadhq** [comment]
Great, thanks for the feedback, makes sense :-)

Assuming I've got this worked out now, I'm going to get started on the moment/timezone stuff as well.

Thanks again

**Comment by Deraen** [comment]
Thanks. Merged, made small changes and released.

**Comment by Deraen** [comment]
@chadhq Btw. while your are looking into Moment stuff, I think Moment.js extern could also use improvements: #6 :)

**Comment by chadhq** [comment]
@Deraen Sure, I'll take a look.

Thanks for that.

**Pull request merged**
