### PR TITLE
jqGrid 5.0.0 cljsjs package

### PR DESCRIPTION
**Pull request by gberenfield**
jqGrid cljsjs package for jqGrid 5.0.0
Tested with compilation set to ```:none``` and ```:advanced```

### CODE REVIEW

**Comment by Deraen** [comment]
It's practice that the source code for the library shouldn't be included in the repo and instead be downloaded in the package task.

**Comment by gberenfield** [comment]
This uses the repo now and includes locale settings as separate namespaces

**Comment by gberenfield** [comment]
Updated to jqGrid 5.0.1 - requested changes included

**Comment by gberenfield** [comment]
Requested changes made

**Pull request merged**
