### PR TITLE
Add auth0.js library

### PR DESCRIPTION
**Pull request by nhusher**
CLJSJS package for [Auth0.js](https://github.com/auth0/auth0.js)

### CODE REVIEW

**Comment by martinklepsch** [comment]
Hey! Is there a particular reason for the `[cljsjs/auth0 "6.3.0-1-SNAPSHOT"]` in the README?

**Comment by nhusher** [comment]
There totally isn't! An oversight on my part.

**Comment by martinklepsch** [comment]
@nhusher I just went ahead and did it. Thanks for your contribution! :+1:

**Comment by martinklepsch** [comment]
Should be on Clojars now :)

**Comment by nhusher** [comment]
:pizza: × :100:

**Pull request closed without merging**
