### PR TITLE
[gl-matrix] Add gl-matrix library.

### PR DESCRIPTION
**Pull request by jenanwise**
Currently using my own fork of the library because the original hasn't had a proper release in a while. My fork is just a build of their current master, which includes some crucial bug fixes. I wasn't sure how to semver this so I used `MAJOR.MINOR.RELEASE-FORKNAME-0`: `2.3.0-jenanwise-0`.

* Original library: https://github.com/toji/gl-matrix
* Fork: https://github.com/jenanwise/gl-matrix

Test project verifying `:none` and `:advanced` both work: https://github.com/jenanwise/cljsjs-gl-matrix-test

### CODE REVIEW

**Comment by martinklepsch** [comment]
Have you tried convincing them to cut a release? I think what you're suggesting is a valid approach but having a proper release trumps everything :)

**Comment by jenanwise** [comment]
@martinklepsch That would be ideal! But you can see a number of issues, some over a year old, asking for a new release [here](https://github.com/toji/gl-matrix/issues). I have a couple of PRs there fixing their currently-broken build process, which may help towards releases in the future, but I'm not expecting fast movement there. Certainly if the library gets a proper release I'll submit a PR to cljsjs preferring that one.

**Comment by martinklepsch** [comment]
@jenanwise I didn't see any issues specifically asking for a new release. Once there is one created and we can link to that in the package README I'm happy to merge this.

**Comment by jenanwise** [comment]
@martinklepsch Sure I went ahead and made a new explicit request with toji/gl-matrix#156 and added it to this PR with b79abfb.

**Comment by martinklepsch** [comment]
Jenan, thanks for this PR! :beers: 

I merged it and it should be on Clojars now: https://clojars.org/cljsjs/gl-matrix

Have a good day :sunny:

**Comment by jenanwise** [comment]
Many thanks!

**Pull request closed without merging**
