### PR TITLE
[pubnub] Upgrade to pubnub-3.8.0

### PR DESCRIPTION
**Pull request by TerjeNorderhaug**
Supposed to provide support for React native.

### CODE REVIEW

**Comment by Deraen** [comment]
This commit seems to be made against very old Cljsjs master so I'm unable to merge this without conflicts. Please rebase against current master.

**Comment by TerjeNorderhaug** [comment]
Thanks. Sorry about that.

**Comment by Deraen** [comment]
Okay, diff looks good now. Could you still squash the commits into one? (`git rebase -i HEAD~5` and select squash for last four commits).

**Comment by TerjeNorderhaug** [comment]
Commits squashed, although now the diff is a mess.

**Comment by Deraen** [comment]
Huh, that is strange. Anyhow, I updated the package myself.

**Comment by TerjeNorderhaug** [comment]
Thanks.

**Pull request closed without merging**
