### PR TITLE
[exif] add exif.js library

### PR DESCRIPTION
**Pull request by upgradingdave**
This is my first pull request to cljsjs, so if I missed anything or if I can change anything to be more helpful, please let me know. 

Tested in simple and advanced compilation. Here's an example of a widget using this library: http://www.upgradingdave.com/blog/html/exif.html

Thanks, 
Dave

### CODE REVIEW

**Comment by Deraen** [comment]
Looking at the implementation, I think that the extern file is not complete?

I think following properties and methods should be declared in extern: `EXIF.Tags`, `EXIF.TiffTags`, `EXIF.GPSTags`, `EXIF.StringValues`, `EXIF.getTag`, `EXIT.getAllTags`, `EXIF.readFromBinaryFile`. (I did a quick search for `EXIF.` in the file).

**Comment by upgradingdave** [comment]
Good call, I only put in what I needed, I'll add those to the ext as soon as I have a chance, thanks!

**Comment by upgradingdave** [comment]
I updated the externs file, please let me know if I can clean anything else up. Thanks again.

**Comment by Deraen** [comment]
Looks good. Thanks for contribution!

**Pull request merged**
