### PR TITLE
[vis] Updated to v4.9.0

### PR DESCRIPTION
**Pull request by ducky427**

### CODE REVIEW

**Comment by martinklepsch** [comment]
Thanks!

**Comment by ducky427** [comment]
Thanks a lot @martinklepsch! :+1:

**Comment by ducky427** [comment]
Hi @martinklepsch,
I just checked the vis.js package on clojars and it seems that it is missing the development and production javascript even though when I run `boot package build-jar` locally the correct package is built.

Thanks

**Comment by martinklepsch** [comment]
@ducky427 I think I'm at fault for this. Will push `-1` in a sec. (I think I just did `boot build-jar push-release` instead of also running the `package` task :smirk:)

**Comment by ducky427** [comment]
Thanks a lot @martinklepsch. much appreciated!

**Comment by ducky427** [comment]
I can confirm that in `4.9.0-1` the issue is fixed. cheers!

**Comment by martinklepsch** [comment]
Great, thanks for the confirmation!

**Pull request closed without merging**
