### PR TITLE
added highcharts

### PR DESCRIPTION
**Pull request by gbuisson**
Hi, 

I made a basic Highcharts package, no fancy stuff and no externs annotations.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Hey, for easier maintainability I'd suggest structuring the `build.boot` file similar to as it's structured in other packages. Also make sure you add a `-0` version suffix for incremental CLJSJS releases.

**Comment by kenfehling** [comment]
This build.boot should be more in line with conventions.

**Comment by martinklepsch** [comment]
This looks good.

**Comment by martinklepsch** [comment]
Or, wait. This downloads an unversioned js file that might change do I see that right?

**Comment by kenfehling** [comment]
Ohhh... yeah I suppose that's true.

**Comment by martinklepsch** [comment]
I'm fixing it.

**Comment by kenfehling** [comment]
OK, thank you.

**Comment by martinklepsch** [comment]
I just merged and published `[cljsjs/highcharts "4.1.8-0"]`. Unfortunately author information for your commit got lost during a rebase @kenfehling. I'm sorry about that, hopefully you don't mind. 

Thanks for your contributions Ken & @gbuisson.

**Pull request closed without merging**
