### PR TITLE
added webcomponents(-lite) & Updates to Material version

### PR DESCRIPTION
**Pull request by flyboarder**
Untested PR for webcomponents(-lite) using cloud flare CDN.

### CODE REVIEW

**Comment by flyboarder** [comment]
Tested and appears working. Please let me know if things need to change. :smile:

**Comment by flyboarder** [comment]
Also updated Material version, closes #252

**Comment by Deraen** [comment]
The changes look good. Would be great if you could rebase this against master and squash the three webcomponents commits into one commit.

**Comment by Deraen** [comment]
Seeing that Material has been updated to 1.0.6 here now, I'm not going to resolve the conflicts my self. Please update and test the PR.

**Comment by flyboarder** [comment]
Thanks!! It's been a busy week, if you don't get to it today I can complete this on the weekend.

Sent from Outlook




On Fri, Nov 27, 2015 at 10:31 AM -0800, "Juho Teperi" <notifications@github.com> wrote:












Seeing that Material has been updated to 1.0.6 here now, I'm not going to resolve the conflicts my self. Please update and test the PR.

**Comment by flyboarder** [comment]
Closing, superseded by #445.

**Pull request closed without merging**
