### PR TITLE
JSZip library

### PR DESCRIPTION
**Pull request by skrat**
Would this be a nice addition?

### CODE REVIEW

**Comment by skrat** [comment]
Seems @martinklepsch is on holiday, could anyone look into merging this? @jeluard ?

**Comment by jeluard** [comment]
I'm not part of `CLJSJS` core team so I'd rather let @martinklepsch take a look.

**Comment by martinklepsch** [comment]
Two things:
- please make sure the version has an appended "-0" for initial releases.
- one of your sift calls contains a reference to `gl-matrix`.

After those are fixed we can probably merge this.

**Comment by skrat** [comment]
@martinklepsch  I had to add the `exports=undefined` to make it work in the environment where I use it. If anyone using `cljsjs.jszip` founds it problematic, we can re-evaluate the issue.

**Comment by martinklepsch** [comment]
Is this potentially relevant? http://mneise.github.io/posts/2015-06-08-week-2.html

I'm not yet sure how this fits together with CLJSJS but sooner than later that's probably worth investigation. I hope I'll get to merging this today.

**Comment by skrat** [comment]
It sure is. Honestly I don't see a point in developing anything CommonJS related in CLJS, because ECMA already standardized on a module system in ES6.

**Comment by skrat** [comment]
@martinklepsch Is there any issue merging and publishing this?

**Comment by martinklepsch** [comment]
No, I think we can probably merge this. I'm just at euroclojure right now
and haven't opened my laptop for the last 2 days.
Sorry for being a bit slow here :o)

**Comment by skrat** [comment]
Still there? :)

**Comment by skrat** [comment]
Hi @martinklepsch . This project is not working, if it would, this would be already merged and published on clojars. Could someone else do it, or are you the only one in charge?

**Comment by martinklepsch** [comment]
Merged and deployed to Clojars via https://github.com/cljsjs/packages/commit/22a48afe68d1c3b9c398ecdf26809f0e0f13ba3b. 

There are a few other people with commit and Clojars access but all of us maintain this stuff in our spare time. If this project is not working for you or you see a better way of doing things you're always free to find another way.

**Pull request closed without merging**
