### PR TITLE
[js-joda-timezone] Updated to 2.21.1

### PR DESCRIPTION
**Pull request by bgalartza**

### CODE REVIEW

**Comment by henryw374** [comment]
hi. it says branch has conflicts to be resolved

**Comment by bgalartza** [comment]
> hi. it says branch has conflicts to be resolved

Sorry, didn't realized. Fixed now.

**Comment by bgalartza** [comment]
Ups, now check-sums failing. Fixing it now. Sorry again.

**Comment by bgalartza** [comment]
All good now.

**Pull request merged**
