### PR TITLE
Initial wrapping of three-water-material

### PR DESCRIPTION
**Pull request by timothypratley**
Hi,
This is a pretty niche library, but I found it useful... it provides a nice water material for threejs scenes.

### CODE REVIEW

**Comment by Deraen** [comment]
Unless there is some reason, it think this should use the same name as original packaging uses: `ocean`.

**Comment by timothypratley** [comment]
@Deraen would three-ocean be O.K.?
I'm fine with ocean, just suggesting it will be easier for people to find threejs related wrappers, seeing in this case it is highly threejs specific... what do you think?

**Comment by Deraen** [comment]
@timothypratley I guess it's okay. I still would prefer just `ocean`. Description already mentions Three.js.

**Comment by timothypratley** [comment]
O.K. just `ocean` it is :) will rename.

**Pull request merged**
