### PR TITLE
React-autosuggest updated  to v9.3.2

### PR DESCRIPTION
**Pull request by zarsky-broad**
Commit and PR based on https://github.com/cljsjs/packages/pull/1085.

Minimal api change, https://github.com/moroshko/react-autosuggest/releases/tag/v9.3.2

**Extern:** The API did not change.

### CODE REVIEW

**Comment by zarsky-broad** [comment]
I can't figure out why this is failing on circle. It works locally.

**Comment by Deraen** [comment]
Which node/npm are you running locally? Try with Node 8 / NPM 5.

```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle react-autosuggest@9.3.2~prepublish: cannot run in wd %s %s (wd=%s) react-autosuggest@9.3.2 npm run dist && npm run standalone /root/.boot/cache/tmp/root/cljsjs/react-autosuggest/4l7/-i61w3b/react-autosuggest-9.3.2
```

**Comment by zarsky-broad** [comment]
Interesting point, @Deraen. So, I tried running manually in the Docker image that Circle uses with the current state of `master`, and that same error occurs when running `boot package`. FWIW, I'm running the Node LTS, which is currently 6, locally, but it looks like that may actually be a permission issue…?

**Comment by zarsky-broad** [comment]
@Deraen I figured it out! Since the user running `boot package` is `root`, `npm install` needs to be granted explicit permission to run scripts as `root` so they can access the temp directory boot creates. `--unsafe-perm` does that.

**Comment by Deraen** [comment]
Cool. I also added global env variable to set this option, so packages don't need to care about this: https://github.com/cljsjs/packages/commit/25fb3bc2efaab88892f897cb34aa91b4174ebc06

**Comment by zarsky-broad** [comment]
Fantastic. Thanks very much!

**Pull request merged**
