### PR TITLE
Update mui to 0.1.8

### PR DESCRIPTION
**Pull request by mynomoto**

### CODE REVIEW

**Comment by martinklepsch** [comment]
Do I understand correctly that externs are not needed for the `mui.js` file because you will never directly call any of the functions in there?

**Comment by mynomoto** [comment]
Yes, that's it.

**Comment by Deraen** [comment]
How are you then using this? Is it only for CSS?

**Comment by mynomoto** [comment]
Loading the library add event listeners for changes on DOM then it changes elements with specific classes.

**Comment by Deraen** [comment]
Okay.

**Pull request merged**
