### PR TITLE
Upgrade ECharts to v3.2.2

### PR DESCRIPTION
**Pull request by apterf**
**Extern:** I updated the extern with generator.

### CODE REVIEW

**Comment by ducky427** [comment]
@apterf, the PR doesn't include the updated externs.

**Comment by Deraen** [comment]
@apterf Could you confirm the status of externs, if you generated new externs are the identical to the old, or is the PR missing the updated extern?

**Comment by apterf** [comment]
Hi Sorry just saw the message.
I checked and got some problems when generating the externs for [zrender/3.1.2](https://github.com/ecomfe/zrender/tree/3.1.2) . ;(

**Comment by kirked** [comment]
Can this be updated to 3.3.1 (latest) before merging?

**Comment by Deraen** [comment]
@kirked As the original author has not touched this is a while, I recommend finalizing this yourself if you need this package.

You can checkout the code in this PR to existing packages clone like this:
```bash
git checkout -b apterf-master master
git pull https://github.com/apterf/packages.git master
```

**Comment by Deraen** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
