### PR TITLE
[d3] Update d3 externs

### PR DESCRIPTION
**Pull request by rtaboada**
Update:

**Extern:** I updated the extern by hand.

Updated all `d3-force` objects to have all the appropriate functions and also updated `d3.zoom`.

### CODE REVIEW

**Comment by ducky427** [comment]
@rtaboada, could you squash all the commits into one?

**Comment by ducky427** [comment]
You may also want to document on the top of the file that some of the externs were done by hand.

**Comment by rtaboada** [comment]
@ducky427 Done.

**Comment by ducky427** [comment]
cheers!

**Pull request merged**
