### PR TITLE
Three.js R72

### PR DESCRIPTION
**Pull request by sonwh98**
updated to latest release version of three.js r72

### CODE REVIEW

**Comment by martinklepsch** [comment]
Hey, thanks for updating this! :) Looking at the release notes it seems that there are new objects and methods being added to the library, could you look into updating the externs as well?

**Comment by sonwh98** [comment]
added the externs. is there a better way to do this? These externs should be auto generated from the js source

**Comment by sonwh98** [comment]
Is there anything I can do to get expedite the merging of this pull request?

**Comment by martinklepsch** [comment]
Hey @sonwh98 — sorry for the delay on this one.

If you could squash the commits and use the pattern used by other commits in the repo I can merge this later today. 

Pattern is `[three] description of your changes' :) 

As for a better way of creating externs: there are basically two options: write them yourself or generate them. Generating could be added to cljsjs tooling in one way or another but so far no one has tackled that.

**Comment by sonwh98** [comment]
I created a new pull request in three-r72 branch with the commit squashed. never used squash feature of git before so let me know if i did something incorrectly

**Pull request closed without merging**
