### PR TITLE
Adds airbnb/enzyme

### PR DESCRIPTION
**Pull request by agzam**
This is my very first attempt to create a cljsjs package (please criticize - so I can learn). I desperately need to make it possible to use Enzyme in browser environment.

I need help with improving this package:

a) it currently only works with React 15
b) I was trying to find a way to use Global exports feature https://clojurescript.org/news/2017-07-30-global-exports ,so it could be required like this:

    (require '[cljsjs.enzyme :as enzyme])

but couldn't figure it out

### CODE REVIEW

**Comment by Deraen** [comment]
Please go back to `deps-cljs`. If you want to use global-exports, update boot-cljsjs to 0.8.1.

**Comment by agzam** [comment]
@Deraen Can you elaborate? You mean I should not be using deps.cljs? Why's that?

**Comment by Deraen** [comment]
`deps-cljs` task is less lines and one less file, and ensures that file paths etc. are correct.

**Comment by agzam** [comment]
@Deraen
This is ready to be merged. 
I hope you've seen my comment in Slack https://clojurians.slack.com/team/U0G75ARHC
I got back where I started (no global-exports). I guess I'm gonna write a wrapper in my app (that would be using this package), something like this:

    (ns app.enzyme
      (:require [cljsjs.enzyme]
                [reagent.core :as reagent]
                [reagent.ratom :as ratom]))

    (defn- wrapper [enzyme-fn form]
      (let [element (reagent/as-element form)
            node (enzyme-fn element)]
        {:root node
        :node node}))

    (defn shallow [form]
      (wrapper js/enzyme.shallow form))

    (defn mount [form]
      (wrapper js/enzyme.mount form))

    (defn simulate! [event-type {:keys [node root] :as wrapper}]
      (.simulate node event-type)
      (ratom/flush!)
      (reagent/flush)
      (.update root))

**Pull request merged**
