### PR TITLE
Update to new release of openlayers (v3.2.0)

### PR DESCRIPTION
**Pull request by olivergeorge**
Also fixes issue with missing ol.ext.rbush

### CODE REVIEW

**Comment by martinklepsch** [comment]
@olivergeorge did you test that requiring `ol.ext.rbush` works as it should? If so you're welcome to hit the merge button :)
Do you have an account on Clojars and are familiar with deploying jars to it with boot? If so I can also add you to the cljsjs group on Clojars.

**Comment by olivergeorge** [comment]
Great. Done.  

I'm not on clojars yet.  I'll follow up when I am.

Thanks for your help.

**Comment by olivergeorge** [comment]
Hi Martin

I've registered on clojars.  I'm "olivergeorge".  I haven't deployed with
boot but happy to read up.

cheers ,Oliver

**Comment by martinklepsch** [comment]
Great. I added you to the group. If you're stuck trying to figure out how
to deploy with boot feel free to come int #hoplon on IRC and ask how to do
it. :)

**Comment by olivergeorge** [comment]
Thanks, I have a busy couple of days ahead of me.  I'll probably surface
again late in the week.

**Comment by martinklepsch** [comment]
Sure, take your time :)

**Pull request merged**
