### PR TITLE
Add packages react-input-autosize and react-select

### PR DESCRIPTION
**Pull request by wavejumper**
This pull request adds packages for [react-select](https://github.com/JedWatson/react-select) and [react-input-autosize](https://github.com/JedWatson/react-input-autosize) (a dependency of react-select)

I had to fork react-select because of https://github.com/JedWatson/react-select/issues/526  - so the package currently points to my fork.

### CODE REVIEW

**Comment by olivergeorge** [comment]
Hi, just looking to try react-select.  I'll give this a go.  

I note that the ticket you mentioned is resolved... that might mean we don't need a forked repo for this.

**Comment by wavejumper** [comment]
Correct. When a release is pushed with this change in place I will update my pull request :)

**Comment by Deraen** [comment]
What's the status? Does this still refer to a fork?

**Comment by atroche** [comment]
Yep, and it looks like the fix for https://github.com/JedWatson/react-select/issues/526 won't be available until a new release of react-select. Unless we're willing to base the cljsjs package off master…

**Comment by Deraen** [comment]
I have merged #310 which added the same packages with more recent versions. Hopefully this can be closed?

**Comment by atroche** [comment]
good work =) makes sense to me

**Pull request closed without merging**
