### PR TITLE
Update react-select beta6 -> beta10

### PR DESCRIPTION
**Pull request by sp3ctum**
The whitespace changes look weird to me. I think I'm using standard emacs clojure-mode settings for the indentation.

### CODE REVIEW

**Comment by sp3ctum** [comment]
Uh, looks like the CI might be stuck on some test environment issues.

**Comment by Deraen** [comment]
You based your PR on a commit from December and that problem has been fixed in later test/build scripts. You should rebase the changes into latest master.

**Comment by sp3ctum** [comment]
Closing and submitting a new PR

**Comment by sp3ctum** [comment]
New PR is https://github.com/cljsjs/packages/pull/432
(just trying to make this less confusing)

**Pull request closed without merging**
