### PR TITLE
[highlight] Add instructions about adding theme CSS to projects

### PR DESCRIPTION
**Pull request by anmonteiro**
Add instructions on how to add CSS to highlight.js users

### CODE REVIEW

**Comment by Deraen** [comment]
I think it would be better to link to this wiki page: https://github.com/cljsjs/packages/wiki/Non-JS-Assets

Additionally you could mention this pure `sift` solution before `from-jars` task example.

**Comment by anmonteiro** [comment]
I was just following the lead of the CodeMirror's [README](https://github.com/cljsjs/packages/blob/master/codemirror/README.md), which has similar instructions. I'm happy to change it to link to the wiki, if that's how I should proceed.

**Comment by Deraen** [comment]
Yeah, it is best to link to the wiki page from every readme.

**Comment by anmonteiro** [comment]
@Deraen updated the PR with your feedback

**Pull request merged**
