### PR TITLE
Arichiardi add intersections

### PR DESCRIPTION
**Pull request by Deraen**
Replaces #974

### CODE REVIEW

**Comment by arichiardi** [comment]
Looks good! I will try in my project on Monday. The only thing that I noticed is that externs change a bit and I could not make the [generator](https://github.com/jmmk/javascript-externs-generator) work.

**Comment by Deraen** [comment]
@arichiardi In fact I think most of the externs are unncessary as the package only exposes `intersect` and `shape`: https://github.com/signavio/svg-intersections/blob/master/index.js

**Comment by arichiardi** [comment]
Oh right, the example is a bit different as there is no `Point2D` exposed
anymore...

See on the README: https://github.com/signavio/svg-intersections

**Comment by Deraen** [comment]
Yep, I updated the example to match that.

**Comment by Deraen** [comment]
There is another fork also: https://github.com/Quazistax/kld-intersections but I don't think that has any releases, and it is also using old dependencies. Hopefully fork I packaged works, as I much prefer to package version with proper release.

**Comment by arichiardi** [comment]
Wow quick! :D Thanks a lot for that! The library is very useful and I am
happy we found a solution that is good. So for the feature, should I prefer
shelling out to node for these things?

**Comment by Deraen** [comment]
For creating browser compatible libraries from Common JS modules? Yes, I think browserify is usually good enough solution and doesn't require much configuration. Webpack is good solution when the package provides existing configuration.

**Comment by arichiardi** [comment]
I have tried that, not very up to date, and the maintainer of
`kld-intersections` even sent an email back to me, that is why I picked it
:)

**Comment by arichiardi** [comment]
Yes, cool I am going to close the other one then. Thanks I will follow that
path.

**Comment by Deraen** [comment]
@arichiardi Have you had time to test this?

**Comment by arichiardi** [comment]
Hey Juho, no but soon, I have been stuck on some other task. Sorry about that!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Deraen** [comment]
ping @arichiardi

**Comment by arichiardi** [comment]
Thanks for pinging,. Ihaven't had time yet, sorry, other tasks are taking all my time atm, it is scheduled of course 😀

**Comment by Deraen** [comment]
ping @arichiardi 

I think I tested this myself so I'm thinking about just merging this to get the PR closed :)

**Comment by arichiardi** [comment]
Agree, I think it safely mergeable 😀
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
