### PR TITLE
[react-mdl] moving css assets to public/assets

### PR DESCRIPTION
**Pull request by Shearerbeard**
Changed bathing for css assets in jar to move to a public directory for client side projects.

### CODE REVIEW

**Comment by martinklepsch** [comment]
hey @Shearerbeard, thanks for your contribution. Generally we want to keep things under a predictable namespace/directory (i.e. `cljsjs/`). Users then need to move files to the places they need them or setup handlers to serve them on their own. There's a bit of documentation about this in the wiki, if you're using Boot this will be easy :smile: https://github.com/cljsjs/packages/wiki/Non-JS-Assets

A change like this may seem handy but its impossible to anticipate all the setups people will have and thus consistency/predictability is the better option IMHO.

Let me know if you have further questions. :)

**Comment by Deraen** [comment]
Just created https://github.com/Deraen/ring-cljsjs (will be available in Clojars once I get GPG to co-operate).

**Comment by Shearerbeard** [comment]
Awesome Juho, this is a great solution to serve other static assets from cljsjs packages.

**Comment by Deraen** [comment]
Available now https://clojars.org/ring-cljsjs

**Pull request closed without merging**
