### PR TITLE
Adds firebase-node and bumps to 3.2.1

### PR DESCRIPTION
**Pull request by timothypratley**
Pending discussion:

This would bring firebase-node into the firebase package (if this is held to be desirable)...
This is closer to how npm packages firebase+firebase-node.

Notably I am not a firebase-node user, so please complain if this seems bad.
(I have not adequately test firebase-node, I need to spend some time on it... soon I hope! If you do use firebase-node and can try it out that would be much appreciated)
cljsjs/firebase itself seems fine for my usage of it.

### CODE REVIEW

**Comment by timothypratley** [comment]
I'm thinking of concatenating all the externs files into a single .ext.js file to avoid https://github.com/cursive-ide/cursive/issues/1477

**Comment by Deraen** [comment]
@timothypratley What is the status of this PR? Should I merge this?

**Comment by timothypratley** [comment]
@Deraen I think it can move ahead, but also it wouldn't hurt to wait a couple of days for comments or objections.

**Comment by flyboarder** [comment]
lgtm 👍

**Pull request merged**
