### PR TITLE
[WIP] cljsjs/react-toolbox

### PR DESCRIPTION
**Pull request by lwhorton**
New package:

**Extern:** Written by hand.

### CODE REVIEW

**Comment by ducky427** [comment]
I think there are a few things wrong with package:

1. This package should have `cljsjs.react` or `cljsjs.react-with-addons` as a dependency.
1. There is no need for `deps.cljs` file.
1. Are you sure about the syntax of `react-addons-css-transition-group` as an external dependency in the webpack file?

**Comment by lwhorton** [comment]
1. Thanks. I wasn't sure if that should or should not be a dep.
2. I'm unclear on why some packages have a deps and some do not (and why does this one not?).
3. No, you're correct. I thought css-transition-group was an external package but after poking around on the react docs (not very clear) and confirming in the code, it seems it's still under `React.addons`... and thus the webpack should not expose that as an external dep.

**Comment by lwhorton** [comment]
Per the help of @ducky427 and @martinklepsch on clojarians.slack, I think the latest rebase has fixed all the issues.

**Comment by lwhorton** [comment]
More issues fixed:

1. failure to `:requires` react has been fixed. **note** that I'm not 100% sure if this should be `cljsjs.react-with-addons` (or some variant `react.with-addons`, etc), but addons seems to be packaged under `cljsjs.react`. I could find no example in other packages mentioning -with-addons.
2. webpack build must list the `css-transition-group` as an external, but this is awkward because `react-with-addons` brings the dependency, and `-css-transition-group` has to "read it in" from the environment.
3. removed deps.cljs in the sift task, which is not needed

**Comment by ducky427** [comment]
LGTM. 👍

**Comment by lwhorton** [comment]
Actually using this in an implementation I ran into an issue with selector specificity. Since in cljsjs land we cannot easily use webpack to write sass to customize components, this library pre-builds components a single importable object. Those pre-built components, when imported, attach a `<style>` tag to the head, thus achieving "plug-n-play" interop. However, by default the style tags are added to the bottom of the head... which causes havoc when providing custom themes from some css module elsewhere. This simple fix puts the tags at the head, so user-land css-modules can effectively overwrite predefined styles.

**Comment by Deraen** [comment]
I don't think it is a good idea to automatically add stylesheet to HTML. Instead just provide single css (and less/sass if possible) file in the package, that users can include on their own, using [ring-cljsjs](https://github.com/Deraen/ring-cljsjs) or boot-sass/less etc.

**Comment by lwhorton** [comment]
I absolutely agree, and thats part of why this remains a WIP. The problem unfortunately is a little more effort to solve than I hoped. The lib uses sass preprocessing with webpack as almost a prerequisite. [Check here](https://github.com/react-toolbox/react-toolbox/issues/597#issuecomment-231174695) for some more thoughts. I agree with the  sane solution listed (although a lot of work): expose a stylesheet using bem instead of css modules, then allow consumers to override as needed. 

~luke

**Comment by lwhorton** [comment]
I no longer believe this is a good idea. css modules intermixed with cljs, webpack preprocessors, and inline style tags is just too complex and doesn't feel very clojure-ey. I can't come up with a good scheme to export components appropriately so they're flexible without imposing a *whole* lot of implementation burden details on to consumers. Re-creating the entire library inside my app as straight hiccup took about 4 days of effort, for those curious, and the outcome was much cleaner.

**Pull request closed without merging**
