### PR TITLE
Add phaser.io package

### PR DESCRIPTION
**Pull request by dparis**
Adds a cljsjs package of the [phaser.io](http://phaser.io/) HTML5 game library.

The surface area of this library is pretty large, and as such the externs are long, gnarly, and auto-generated for now. I used the [javascript-externs-generator](https://github.com/jmmk/javascript-externs-generator) tool, and will keep an eye out for bits which might have been missed or require hand-tweaking. 

Along with the Phaser.* namespace, the externs also define the PIXI namespace exposed by the Phaser lib. Since Phaser frequently wraps PIXI objects, there's a high likelihood that a cljsjs/phaser consumer will need to reference the base PIXI functions.

Let me know if this looks good!

### CODE REVIEW

**Comment by dparis** [comment]
@martinklepsch Any idea when you might be able to review and/or merge this? I've been working on a wrapper library for phaser which pulls this cljsjs project in as a dependency, so deployment of that is blocked by the availability of this package. No rush, just trying to get an idea of when I can deploy and start getting feedback on the project.

Also, does it actually help for me to include the `phaser.map` file in the dev build of this package? If that isn't supported, I can just remove that line from the `build.boot` file.

**Comment by martinklepsch** [comment]
@dparis finally merged and deployed to Clojars :rocket: 
https://github.com/cljsjs/packages/commit/0f469023c9dfe5924a29577dcad4e938b825bc0f

**Comment by dparis** [comment]
@martinklepsch Thank you much! I'm still curious about the phaser.map file. If I ought to remove it, just let me know and I'll submit a new PR. Cheers!

**Comment by martinklepsch** [comment]
@dparis source maps are currently not supported in `deps.cljs` files.
Logged a ticket against ClojureScript: http://dev.clojure.org/jira/browse/CLJS-1410

**Pull request closed without merging**
