### PR TITLE
[moment] 2.10.6

### PR DESCRIPTION
**Pull request by dialelo**

### CODE REVIEW

**Comment by crisptrutski** [comment]
Quickly scanning the[changelog](https://github.com/moment/moment/blob/develop/CHANGELOG.md#2103-see-full-changelog) I see that two functions have been added (`to` and `toNow`) - would you mind also updating the externs?

Thanks!

**Comment by dialelo** [comment]
I updated the externs file and changed version to latest bugfix release: 2.10.6.

**Comment by crisptrutski** [comment]
Updated version in README and merged in a6d460516be18e8188c5dae156b2a8e4ef7bf653.

Thanks bringing us *up to date* :clock10::clock11::clock1030: :smile:

**Comment by dialelo** [comment]
:smiley: 

Thank *you* for mantaining such a great resource, keep up the excellent work!

**Pull request closed without merging**
