### PR TITLE
Nodejs externs 1.0.4

### PR DESCRIPTION
**Pull request by aJchemist**
I've tested nodejs externs through this. It worked in advanced compilation as I expected. thx for `boot-cljsjs` hard work!

### CODE REVIEW

**Comment by martinklepsch** [comment]
Thanks, this is a great addition. I'd suggest adding something to the readme that explains how to use the package, i.e. there is no need to require and if it's listed as a dependency the externs should be loaded.

Also wondering if the package name is ideal, maybe @crisptrutski has thoughts?

**Comment by crisptrutski** [comment]
Name sounds good to me, `-externs` seems like a good naming convention for this kind of thing.

Interested in the motivations for advanced compilation for node.js and other server contexts. Are there noticeable performance wins?

**Comment by martinklepsch** [comment]
AFAIK advanced brings many execution optimizations besides the plain filesize stuff. E.g. scripts compiled with `simple` will be slower than ones compiled with `advanced`.

**Comment by aJchemist** [comment]
@martinklepsch ping. I've updated `README.md`.

**Comment by martinklepsch** [comment]
Closed via https://github.com/cljsjs/packages/commit/285fe132ff31e6e473c39bd54ec0378b00cebb9f & https://github.com/cljsjs/packages/commit/26f00b558449b405ac1d4ee7ada61e19886493bc. @aJchemist I added a `-0` to the version so we can release patches for the same version :)

Thanks a lot! :+1:

**Pull request closed without merging**
