### PR TITLE
Package highcharts modules

### PR DESCRIPTION
**Pull request by Deraen**
Replaces https://github.com/cljsjs/packages/pull/1217

### CODE REVIEW

**Comment by Deraen** [comment]
@bjconlan Could you please clone this branch, build the package (`boot package install`) and check if requiring `cljsjs.highcharts.highcharts-more` works?

**Comment by bjconlan** [comment]
Sure thing, give me 30 min.

**Comment by bjconlan** [comment]
I couldn't verify if highcharts-more works because of issues loading the highcharts module/interop:

```
Uncaught ReferenceError: Highcharts is not defined
    at data.inc.js:14
    at data.inc.js:16
```

```
...
'use strict';
(function(factory) {
    if (typeof module === 'object' && module.exports) {
        module.exports = factory;
    } else {
        factory(Highcharts);
    }
}(function(Highcharts) {
...
```

**Comment by Deraen** [comment]
Okay, `cljsjs.highcharts` had wrong file paths. Should be fixed now.

**Comment by bjconlan** [comment]
@Deraen Thanks for this. It correctly resolves and loads the highcharts aux packages.

**Pull request merged**
