### PR TITLE
[react-bootstrap] bump to 0.21.2

### PR DESCRIPTION
**Pull request by tscheibl**

### CODE REVIEW

**Comment by martinklepsch** [comment]
@tscheibl Thanks for updating this. Would you mind rebasing against master?

**Comment by tscheibl** [comment]
Sure, I will do that.
I thought it would be ok to merge master in before the push.

**Comment by tscheibl** [comment]
Done!
I did:
git rebase upstream/master  (where upstream is your repo)
git pull
git push
... i hope this is what you wanted.

**Comment by martinklepsch** [comment]
Hey @tscheibl! That wasn't what I was aiming for but it's no problem, I just went ahead and did it. If you want to understand what I was asking for this link seems to provide a good explanation: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by tscheibl** [comment]
Thanks for the instructions. I'll do it that way next time.
Please excuse my ignorance but I'm just in the very beginning of my career as a successful GitHub open source contributor ;)

**Comment by martinklepsch** [comment]
@tscheibl No worries, we're all here to learn :+1:  :)
If you have any other questions feel free to ask any time.

**Pull request closed without merging**
