### PR TITLE
Add x0, x1, y0 and y1 accessors to d3.area object

### PR DESCRIPTION
**Pull request by OliverM**
**Extern:** I updated the extern by hand.

Issue #707 refers

I'm not sure I'm properly respecting the externs conventions here but happy to adjust if not.

### CODE REVIEW

**Comment by ducky427** [comment]
@OliverM, the externs you have added aren't valid js. Could you please fix that?

**Comment by OliverM** [comment]
@ducky427 sorry, should be good now...

Is there a handy guide to creating externs files by hand, covering the various js combinations of objects and functions?

**Comment by OliverM** [comment]
@ducky427 Sorry, just discovered great resources on the wiki, somehow missed them earlier!

**Comment by ducky427** [comment]
@OliverM, one last change and then this looks all good: change `function(_){}` to `function(){}`. 

Also if you could squash the commits into one, it would be really helpful.

Thanks for your patience!

**Comment by OliverM** [comment]
@ducky427 done, thought the functions should reflect their invocation args, sorry! Squashed too.

**Comment by ducky427** [comment]
Thanks a lot. 👍

**Pull request merged**
