### PR TITLE
[pikaday] Update to version 1.5.1

### PR DESCRIPTION
**Pull request by laurio**
**Extern:** The API did not change.

### CODE REVIEW

**Comment by laurio** [comment]
Resolves #1097

**Comment by Deraen** [comment]
This version forces to use Moment.

There was two foreign-libs previously so user could select either `cljsjs.pikaday` and `cljsjs.pikaday.with-moment`, where the only difference was that the latter had dependency on moment so that moment js got evaluated before Pikaday. I'm not sure if this is necessary. Perhaps we could just have single foreign lib without moment require, and user can add that to their own project if they want to use Pikaday with Moment?

**Comment by laurio** [comment]
Yes, providing a single dependency without requiring Moment would be better imo. I updated the pull request.

**Comment by laurio** [comment]
Actually the original issue was caused by a regression in Clojurescript v1.9.518 - i reverted changes in `pikaday/resources/deps.cljs` file now that the issue was fixed in latest Clojurescript release.

**Pull request merged**
