### PR TITLE
[css-layout] add version 0.0.2, with API and extern changes

### PR DESCRIPTION
**Pull request by bobby**
Hi @martinklepsch!

Thanks a ton for cljsjs!  I've refreshed css-layout in this pull request, and am using the locally built JAR with good success.  There was an API change in css-layout (which was actually included in the prior version, too, but was not addressed by externs), which required a change to the externs file.

Could you merge, and deploy to Clojars at your earliest convenience?

Thanks again for cljsjs!
Bobby

### CODE REVIEW

**Comment by bobby** [comment]
Bump!

@martinklepsch any thoughts on this PR?

**Comment by martinklepsch** [comment]
Merged and pushed 

```clojure
[cljsjs/css-layout "0.0.2-0"]
```

**Comment by martinklepsch** [comment]
@bobby and thanks for your contribution! :beers:

**Comment by bobby** [comment]
Thanks for the update, and for cljsjs!

**Pull request closed without merging**
