### PR TITLE
Package react-quill 0.3.0

### PR DESCRIPTION
**Pull request by mbertheau**
I couldn't really confirm whether this works but it looks a lot like reactabular, so I suspect the error on my side somewhere else.

I'd appreciate it if someone could have a look. Thanks!

### CODE REVIEW

**Comment by Deraen** [comment]
Looks okay but you should really test this locally before this is merged.

**Comment by mbertheau** [comment]
After adding the quill dependency I have it basically working now. No other changes were necessary.

**Comment by mbertheau** [comment]
Thanks for merging!

**Comment by Deraen** [comment]
I added build identifier to the version so this is deployed as `0.3.0-0`.

**Pull request merged**
