### PR TITLE
[openlayers] 3.3.0 and fix externs

### PR DESCRIPTION
**Pull request by ul**

### CODE REVIEW

**Comment by martinklepsch** [comment]
@olivergeorge did you also push to Clojars?

**Comment by olivergeorge** [comment]
Hi Martin

Yes, hope that's okay.

https://clojars.org/cljsjs/openlayers

cheers, Oliver

**Comment by martinklepsch** [comment]
Yeah, perfect, just wanted to make sure :)

**Comment by olivergeorge** [comment]
Great.

First time round we missed some externs.  This release updates to the
latest source and also addresses some advanced compile issues.

**Comment by martinklepsch** [comment]
I thought that since its a closure compatible lib externs are not needed?

**Comment by ul** [comment]
I think, in this case externs define things which cannot be inferred by compiler, e.g. names of members of objects which are passed to OpenLayers functions as options from outside world and their getters must not be munged.

**Comment by ul** [comment]
https://github.com/openlayers/ol3/blob/master/externs/olx.js#L7 :
```
/* typedefs for object literals provided by applications */
```

**Pull request merged**
