### PR TITLE
Reactabular 0.6.6

### PR DESCRIPTION
**Pull request by mikesperber**
Depends on lodash, which I just submitted.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Is it possible that this package does not include the project's source files? 
A change like the one indicated in `build.boot` could be handled programatically as done in [the echarts package](https://github.com/cljsjs/packages/blob/master/echarts/build.boot#L27) and others.

**Comment by mikesperber** [comment]
When I submitted the pull request, it needed a minor patch, which was why I didn't download the dist files. The patch was merged upstream yesterday, so I'll see if I can zap the files again and update the pull request.

**Comment by mikesperber** [comment]
Done.

**Comment by martinklepsch** [comment]
Thanks!

**Pull request closed without merging**
