### PR TITLE
[quill] update to 1.2.4 version

### PR DESCRIPTION
**Pull request by szobov**
Update:

**Extern:** The API did not change.

### CODE REVIEW

**Comment by Deraen** [comment]
Based on the changelog, the API has changed: https://github.com/quilljs/quill/blob/develop/CHANGELOG.md#120

**Comment by szobov** [comment]
But it's only experimental APIs changes and it doesn't break normal API. I should add it to extern?

**Comment by Deraen** [comment]
All the new calls should be added to extern, no matter if experimental or not, else someone will try to use them and they suddenly break in production build.

**Comment by Deraen** [comment]
@Szczyp Add `find`, `getIndex`, `getLeaf`, `getLine`, `getLines` to `externs` and I can merge this.

**Comment by Szczyp** [comment]
@Deraen I feel like I shouldn't be here.

**Comment by Deraen** [comment]
Oops, sorry, meant @szobov. Just typed sz and used autocomplete.

**Comment by szobov** [comment]
@Deraen done!

**Pull request merged**
