### PR TITLE
Use the correct object definition notation for externs definitions.

### PR DESCRIPTION
**Pull request by verma**

### CODE REVIEW

**Comment by pandeiro** [comment]
@verma You should additionally update the package to bump the cljsjs version segment, so we can build and release a new artifact.

**Comment by verma** [comment]
I tried updating and pushing the version number changes, not sure what CircleCI is saying.  Version number changes are in though

**Comment by pandeiro** [comment]
Cool @verma, it just looks like a recent commit conflicts so maybe rebase against master? The conflict is just b/c a new uniform version scheme was implemented; should be easy to resolve the conflict.

**Comment by Deraen** [comment]
CircleCI errors are caused by work-in-progress deployment automation which doesn't work yet.

Would be great if you can rebase this, else I can eventually fix the conflicts.

**Comment by verma** [comment]
On it.

**Comment by johnbendi** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Murphy McMahonSent: Saturday, November 14, 2015 12:25 AMTo: cljsjs/packagesReply To: cljsjs/packagesSubject: Re: [packages] Use the correct object definition notation for externs definitions. (#281)Cool @verma, it just looks like a recent commit conflicts so maybe rebase against master? The conflict is just b/c a new uniform version scheme was implemented; should be easy to resolve the conflict. 

—Reply to this email directly or view it on GitHub.

**Pull request merged**
