### PR TITLE
[nvd3] Add nvd3

### PR DESCRIPTION
**Pull request by jessjohn**
Add `cljsjs/nvd3` to `cljsjs/packages`.

http://nvd3.org/

There's lots of other chart libraries in `cljsjs` already, but `nvd3` would be a great addition as well.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Hey Jess, thanks for your work on this :)
The externs look a little sparse — have you used this package in an application compiled with `:advanced`?

**Comment by jessjohn** [comment]
Hey Martin, thanks for following up!

I agree, the externs do look sparse (I used one of the suggested auto generators, so I was skeptical), but using `:advanced` compilation worked just fine. I was able to insert an nvd3 chart into a clone of a lein-cljsbuild example project using :advanced and have the chart render browser side. :)

**Comment by pandeiro** [comment]
Hi @jessjohn -- to use the DotNetWise externs generator, I had to first load D3 and then this library, but then it worked and the result is probably a better bet. I'm pasting here so you can update the externs file in your own branch, okay?

```
var nv = {
    "dev": {},
    "tooltip": function () {},
    "utils": {
        "windowSize": function () {},
        "windowResize": function () {},
        "getColor": function () {},
        "defaultColor": function () {},
        "customTheme": function () {},
        "pjax": function () {},
        "calcApproxTextWidth": function () {},
        "NaNtoZero": function () {},
        "renderWatch": function () {},
        "deepExtend": function () {},
        "state": function () {},
        "optionsFunc": function () {},
        "calcTicksX": function () {},
        "calcTicksY": function () {},
        "initOption": function () {},
        "initOptions": function () {},
        "inheritOptionsD3": function () {},
        "arrayUnique": function () {},
        "symbolMap": {
            "_": function () {}
        },
        "symbol": function () {},
        "inheritOptions": function () {},
        "initSVG": function () {},
        "sanitizeHeight": function () {},
        "sanitizeWidth": function () {},
        "availableHeight": function () {},
        "availableWidth": function () {},
        "noData": function () {}
    },
    "models": {
        "tooltip": function () {},
        "axis": function () {},
        "boxPlot": function () {},
        "boxPlotChart": function () {},
        "bullet": function () {},
        "bulletChart": function () {},
        "candlestickBar": function () {},
        "cumulativeLineChart": function () {},
        "discreteBar": function () {},
        "discreteBarChart": function () {},
        "distribution": function () {},
        "furiousLegend": function () {},
        "historicalBar": function () {},
        "historicalBarChart": function () {},
        "ohlcBarChart": function () {},
        "candlestickBarChart": function () {},
        "legend": function () {},
        "line": function () {},
        "lineChart": function () {},
        "linePlusBarChart": function () {},
        "lineWithFocusChart": function () {},
        "multiBar": function () {},
        "multiBarChart": function () {},
        "multiBarHorizontal": function () {},
        "multiBarHorizontalChart": function () {},
        "multiChart": function () {},
        "ohlcBar": function () {},
        "parallelCoordinates": function () {},
        "pie": function () {},
        "pieChart": function () {},
        "scatter": function () {},
        "scatterChart": function () {},
        "sparkline": function () {},
        "sparklinePlus": function () {},
        "stackedArea": function () {},
        "stackedAreaChart": function () {},
        "sunburst": function () {},
        "sunburstChart": function () {}
    },
    "charts": function () {},
    "logs": function () {},
    "dom": {
        "write": function () {},
        "read": function () {}
    },
    "dispatch": {
        "render_start": function () {},
        "render_end": function () {},
        "on": function () {}
    },
    "log": function () {},
    "deprecated": function () {},
    "render": function () {},
    "addGraph": function () {},
    "interactiveGuideline": function () {},
    "interactiveBisect": function () {},
    "nearestValueIndex": function () {},
    "version": {}
}
```

**Comment by jessjohn** [comment]
Ah, that looks much better, thanks pandeiro! :) 
Updated extern to include d3 externs along with nvd3 externs.

**Comment by jessjohn** [comment]
@martinklepsch @pandeiro Any chance this PR can be merged, or tell me what needs to be updated to get this PR merged ASAP? It's blocking other projects from being completed (don't shoot the messenger).

**Comment by Deraen** [comment]
Merged and deployed.

**Pull request merged**
