### PR TITLE
[jquery] Add modal function

### PR DESCRIPTION
**Pull request by zjhmale**
add modal function 

```clojure
(.modal (js/$ "#id") "hide")
```

@Deraen

### CODE REVIEW

**Comment by Deraen** [comment]
Does jQuery really have modal function?

**Comment by zjhmale** [comment]
raw jquery does not have modal function, but if you work with bootstrap modal windows, you have to call modal function with a jquery object.

**Comment by Deraen** [comment]
Those functions should be defined on bootstrap extern, not on jquery extern.

**Comment by Deraen** [comment]
Also, it has already been defined on bootstrap extern: https://github.com/cljsjs/packages/blob/master/bootstrap/resources/cljsjs/common/bootstrap.ext.js#L32

**Comment by zjhmale** [comment]
my bad...  just find it [here](https://github.com/cljsjs/packages/blob/master/bootstrap/resources/cljsjs/common/bootstrap.ext.js#L32)

**Pull request closed without merging**
