### PR TITLE
Added localforage package.

### PR DESCRIPTION
**Pull request by yamafaktory**
localForage is a fast and simple storage library for JavaScript. localForage improves the offline experience of your web app by using asynchronous storage (IndexedDB or WebSQL) with a simple, localStorage-like API.

### CODE REVIEW

**Comment by martinklepsch** [comment]
I'm wondering if we might just want to call it `localforage` with a lowercase `F` for consistency? Also the exported object does not seem to have the camelCase spelling.

Also to make it perfect nest the `development`, `production` & `common` dirs not just in `cljsjs/` but in `cljsjs/$packagename/` 
```
cljsjs/development/localforage.inc.js
-> becomes
cljsjs/localforage/development/localforage.inc.js
```

**Comment by yamafaktory** [comment]
Thanks for the feedback! You're definitely right about the naming which is also inconsistent on https://github.com/mozilla/localForage (camelCase for project name, then exposed object in lowercase...). I Will change it ASAP.

**Comment by yamafaktory** [comment]
@martinklepsch done!

**Comment by martinklepsch** [comment]
Merged as https://github.com/cljsjs/packages/commit/5f735525c808e424922da091fba0394a0676e230 & published to clojars :+1: 

Thanks Davy! :)

**Pull request closed without merging**
