### PR TITLE
Fix resource directory structure for vega, vega-lite, and vega-embed

### PR DESCRIPTION
**Pull request by jsa-aerial**
OK, I forgot to create a branch for this, but I hope this will still be fine since it is minor change

### CODE REVIEW

**Comment by Deraen** [comment]
Please increment the build number (version part after the dash). This way maintainers only need to merge the PR and don't need to make any changes themselves.

https://github.com/cljsjs/packages/blob/master/CONTRIBUTING.md#creating-pull-requests

**Comment by Deraen** [comment]
@jsa-aerial Yes, that's it.

**Comment by jsa-aerial** [comment]
If this works, in the near future I want to update these to new versions. When I do that, should these all be set back to "-0"???

**Comment by Deraen** [comment]
@jsa-aerial Yes. I tried to improve document package update process a bit better on the wiki:

> Update package version
> If the upstream library has been updated, update the +lib-version+ on build.boot and set the build identifier part of +version+ var (the part after dash) back to zero.
> If you are only changing the Cljsjs packaging part, like externs, increment the build identifier.

https://github.com/cljsjs/packages/wiki/Updating-packages

[Contributing.md](https://github.com/cljsjs/packages/blob/master/CONTRIBUTING.md#creating-pull-requests) also mentions updating build identifier.

**Pull request merged**
