### PR TITLE
Naive attempt at adding topojson

### PR DESCRIPTION
**Pull request by pcn**
Using d3 as a template, package definition for topojson.

I'm not certain how well this works.  I'm completely new to this, so please don't merge without looking and letting me know what needs to be fixed.

### CODE REVIEW

**Comment by martinklepsch** [comment]
does this depend on `d3`? If so please make sure `cljsjs/d3` is listed as dependency and in `:requires` in the `deps.cljs` file. (See `boot deps-cljs -h` for help)

**Comment by pcn** [comment]
Is the output of "npm install" for the package enough to determine the dependencies?

```
npm install topojson
topojson@1.6.18 node_modules/topojson
├── queue-async@1.0.7
├── rw@0.1.4
├── optimist@0.3.7 (wordwrap@0.0.2)
├── shapefile@0.3.0 (iconv-lite@0.2.11)
├── d3@3.5.5
└── d3-geo-projection@0.2.13 (brfs@1.4.0)
```

**Comment by pcn** [comment]
I think the above isn't quite what you were asking for.  I'm looking around existing bits of the repo for examples.

**Comment by pcn** [comment]
I've included the deps as generated by "boot.sh package" created by adding the cljsjs/d3 dependency from the build.boot.  It's probably clear that I'm missing important bits in my cognitive model of how this all should work, so I'm probably basically cargo-culting things I don't understand here.

Please let me know what is left for me to do, I'd like to have a better understanding of this.

**Comment by martinklepsch** [comment]
@pcn I'll try to write up some general information to help with contributing to CLJSJS this week. Hope this will help :smiley:

**Comment by pcn** [comment]
Ask me whatever you need - I'm really hoping to get this working for me so I can learn some stuff here with whatever free time I've got.

Part of the documentation that would be helpful is how to run a fork of cljsjs while testing in a way that lein cljsbuild can use it, or how to fake that ability somehow.

**Comment by pcn** [comment]
Looks like @pandeiro took care of this.  Closing.

**Comment by martinklepsch** [comment]
@pandeiro @pcn :+1:

**Pull request closed without merging**
