### PR TITLE
[recharts] Add Recharts library

### PR DESCRIPTION
**Pull request by anmonteiro**
New package:

**Extern:** Generated.

### CODE REVIEW

**Comment by ducky427** [comment]
My comments:

1) `README.md` has a reference to `cljsjs/bootstrap`. It should probably be `cljsjs/recharts`.
2) This library seems to have no dependency to react. Is react packaged with it or is that an oversight?

**Comment by anmonteiro** [comment]
1) fixed

2) added `:requires [cljsjs/react]`, definitely an oversight

**Comment by ducky427** [comment]
@anmonteiro, really sorry but 2) isn't done. You need to add it in: `build.boot` in `set-env!` `dependencies` as well, much as [this](https://github.com/cljsjs/packages/blob/master/react-virtualized/build.boot#L4)

**Comment by anmonteiro** [comment]
@ducky427 gotcha, wasn't aware. Which version of React should it depend on? Does it depend on the library itself, or should it be the latest, or something else?

**Comment by ducky427** [comment]
I'd say the version the library depends on. 

React API is pretty stable. So shouldn't be an issue. but still best to stick with what `rechart` authors have tested against.

**Comment by anmonteiro** [comment]
@ducky427 updated the PR with React 15.3.1-0
Recharts specifies peer dependencies of "^14.0.0 || ^15.0.0" so the latest is OK

**Comment by ducky427** [comment]
Thanks!

**Pull request merged**
