### PR TITLE
OpenLayers as native Closure library

### PR DESCRIPTION
**Pull request by martinklepsch**
@olivergeorge @jeluard Please let me know if you think the README could be improved somehow.

### CODE REVIEW

**Comment by jeluard** [comment]
That looks good! I will probably add some details about providing configuration options to reduce generated JS size but I need to find some time to experiment first.

**Comment by martinklepsch** [comment]
> configuration options to reduce generated JS size

What do you have in mind there? I'm thinking `:advanced` is all you can get.

**Comment by jeluard** [comment]
OL3 has a number of [defines](https://github.com/openlayers/ol3/blob/master/src/ol/ol.js) you can set to disable some features (like webgl renderer). Those can be provided to the ClojureScript compiler via [:closure-defines](https://github.com/clojure/clojurescript/wiki/Compiler-Options#closure-defines).

Apparently the benefit is pretty big.

**Comment by martinklepsch** [comment]
Interesting, didn't know about this. Curious to see what the effects are :)

**Comment by olivergeorge** [comment]
Wow, a lot happened while I slept.  Well done guys.

I'll run a few tests today.

**Comment by olivergeorge** [comment]
Well my updated example works.  File size is reduced to 240k as expected.  Looks like you've nailed it.

https://github.com/condense/example_openlayers_cljsjs/tree/master/hellool

Yes, the CSS file would be good.  Wasn't sure if there was a system for static assets yet.

**Comment by olivergeorge** [comment]
@jeluard look forward to seeing how :clojure-defines work

**Comment by jeluard** [comment]
I went down to 200k with the following configuration added to `:compiler`:
```clojure
:closure-defines {:goog.DEBUG false
                  :ol.ENABLE_DOM false
                  :ol.ENABLE_VECTOR false
                  :ol.ENABLE_PROJ4JS false
                  :ol.ENABLE_WEBGL false}}
```

I was expecting better results but at least it's something!

**Comment by olivergeorge** [comment]
Nice to know the knobs are there.  Did you put that in your project.clj or
the package deps.clj?

**Comment by jeluard** [comment]
In `project.clj` in the same map where `:optimizations :advanced` is located.

**Comment by olivergeorge** [comment]
I think your tweak was a ~28% filesize improvement...

* 99k    Hello world
* 240k   OL with getting started example
* 200k   OL with getting started example with things disabled

**Comment by jeluard** [comment]
Just noticed OL3 v. `3.2.0` has been released!

Another thing is the huge number of warnings generated during compilation. It is due to some non regular JSDoc annotations being used.
Closure compiler can be configured to accept [extra annotations](http://javadoc.closure-compiler.googlecode.com/git/com/google/javascript/jscomp/CompilerOptions.html#setExtraAnnotationNames(java.lang.Iterable)). That's not yet configurable at the ClojureScript compiler level but could easily be added.

Now the tricky part is that it should be configured at the library level so that end user don't have to mess with that. Is there some mechanism that would allow those to be defined at the library level, merged then used by the ClojureScript compiler?

**Comment by martinklepsch** [comment]
I don't think there's a mechanism for that. Users should pass 
```
:closure-warnings {:non-standard-jsdoc :off}}
```
to the Clojurescript compiler if they want to hide them.

**Comment by jeluard** [comment]
Right but then you miss all potential errors. Something like `:closure-extra-annotations #{"api"}` would be an improvement.
Still it forces all library consumers to add this configuration which is a little sad.

**Comment by martinklepsch** [comment]
> Right but then you miss all potential errors.

In that special case I don't think this can lead to actual errors(?)

In any case packages should under no circumstances be able to modify your build configuration.
So the solution to this is that the packages README documents useful flags that can be used to make the consumption "smoother".

**Comment by jeluard** [comment]
> In that special case I don't think this can lead to actual errors(?)

It will hide all potential warnings coming from others libraries as this is a global configuration. So it will not introduce errors but might hide some potential ones. Otherwise this config should have `:off` as default value?

> In any case packages should under no circumstances be able to modify your build configuration.

I agree with you for the general case but for some particular config like this one I believe it would make sense. Now it makes this feature pretty complex.

**Comment by martinklepsch** [comment]
> It will hide all potential warnings coming from others libraries as this is a global configuration. So it will not introduce errors but might hide some potential ones. Otherwise this config should have :off as default value?

Only the ones that are about JSDoc tags, I doubt those can be fatal. I assume these warnings are mostly useful for companies like Google to catch typos and make sure code follows some conventions.

**Comment by jeluard** [comment]
Probably. In which case it would make sense to make those warnings off by default. I created [CLJS-1015 ](http://dev.clojure.org/jira/browse/CLJS-1015) to track this point.

**Comment by martinklepsch** [comment]
:+1:

**Comment by olivergeorge** [comment]
Nice work!

**Comment by martinklepsch** [comment]
Rebased, merged and deployed as `[cljsjs/openlayers "3.1.1-1"]`.

**Pull request merged**
