### PR TITLE
Add Tock - an accurate timer library

### PR DESCRIPTION
**Pull request by sp3ctum**
This PR adds the `tock` package to cljsjs.

[Tock](https://github.com/mrchimp/tock) is a self-correcting, accurate JavaScript timer. Typically JavaScript timing can be done with setInterval and setTimeout, but they don't have any guarantees that e.g. a timeout of 1 second will be exactly 1 second.

Tock solves this problem by keeping track of the delay between the expected and actual timeout resolution times, and adjusts its timeout to account for this delay. It may make sense to view Tock's demo which can be found in the link above.

I have been working on my puzzle app called [Squanmate](https://github.com/sp3ctum/squanmate/), where I built a reagent component that uses Tock internally, to keep track of a solve's inspection time. It worked as expected both in development and under advanced optimizations.

That's a pretty long explanation.. Please let me know if there is something more I should do.

### CODE REVIEW

**Comment by sp3ctum** [comment]
Hold on. Just discovered that in my production code, I now see the library as-is (non-minified).

I wonder what caused it, and how it could be fixed.

**Comment by sp3ctum** [comment]
```
± % boot package show --fileset                                                                                                  !5837
Downloading tock.js
Downloading tock.min.js
Sifting output files...
Sifting output files...
Writing deps.cljs
deps.cljs:
{:foreign-libs
 [{:file "cljsjs/tock/development/tock.inc.js",
   :provides ["cljsjs.tock"]}],
 :externs ["cljsjs/tock/common/tock.ext.js"]}
Writing pom.xml and pom.properties...
Writing tock-1.0.12-0.jar...
Checksums match

├── META-INF
│   └── maven
│       └── cljsjs
│           └── tock
│               ├── pom.properties
│               └── pom.xml
├── cljsjs
│   └── tock
│       ├── common
│       │   └── tock.ext.js
│       └── development
│           └── tock.inc.js
├── deps.cljs
└── tock-1.0.12-0.jar
```

It looks like it may be missing the production js from this package. I'll try to poke around to see if I can fix it.

**Comment by ericfode** [comment]
This look awesome! Could you squash your commits and start them with "[Tock]" as per the PR guidelines? https://github.com/cljsjs/packages/blob/master/CONTRIBUTING.md

Ty again!

**Comment by sp3ctum** [comment]
I see now that this PR wasn't quite up to the standards - I must have been too excited to read them thoroughly enough. Thanks for your patience :)

I squashed the commits and submitted this new PR here: https://github.com/cljsjs/packages/pull/1466

**Pull request closed without merging**
