### PR TITLE
Cljsjs jqconsole

### PR DESCRIPTION
**Pull request by arichiardi**
This is a work in progress, because I am not a js expert.
I would like someone to double check as I can't make it work if ```:optimizations :advanced```.

Or better, it works if I manually import the dependencies with:
``` html 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/jqconsole/jqconsole.min.js"></script>
```

Otherwise it gives me the dreaded:
```Uncaught ReferenceError: $ is not defined```

P.S.:
``` [lein-cljsbuild "1.1.0"]```

### CODE REVIEW

**Comment by martinklepsch** [comment]
I don't see any obvious mistakes here. With `:none` everything is working fine? You could also check if the compiled file in `:advanced` contains the contents of any of those two js files at the beginning, what you're saying means none would be prepended.

**Comment by arichiardi** [comment]
Yes with :none everything works fine. Very weird indeed, I will check again. Please don't merge yet.

**Comment by arichiardi** [comment]
I see ```reactjs``` in my compiled ```.js``` but no trace of ```jquery``` or ```jqconsole```. Weird weird weird, any hint? What can have failed?

The ```project.clj``` that includes them goes:

``` clojure

:cljsbuild {:builds [{:id "dev"
                        :source-paths ["src/cljs"]
                        :figwheel {:on-jsload "cljs-browser-repl.core/main"
                                   :css-dirs ["resources/public/styles"]}
                        :compiler {:main cljs-browser-repl.core
                                   :output-to "resources/public/js/compiled/cljs-browser-repl.js"
                                   :output-dir "resources/public/js/compiled/out"
                                   :asset-path "js/compiled/out"
                                   :source-map-timestamp true}}

                       {:id "min"
                        :source-paths ["src/cljs"]
                        :compiler {:main cljs-browser-repl.core
                                   :output-to "resources/public/js/compiled/cljs-browser-repl.js"
                                   :optimizations :advanced
                                   :pretty-print false}}]}

```

```Core.cljs``` starts with:

``` clojure
(ns cljs-browser-repl.core
  (:require [reagent.core :as reagent]
            [cljsjs.jquery :as jq]
            [cljsjs.jqconsole]
            ))
```

**Comment by martinklepsch** [comment]
```
[cljsjs.jquery :as jq]
```
this is not really supported. foreign libs will always be exposed via their name in the global js namespace, i.e. `js/$`. I think it shouldn't cause any trouble but who knows ;)

**Comment by arichiardi** [comment]
Yep sorry it was some experiment, it does not work without as well...in the dev console $ works but I can't see jQuery, or $.fn.jqconsole or $('#something).jqconsole. Who does the present? Should I file an issue at cljsblild guys? Maybe something changed in either yor boot script and cljsblild and the two "cannot see each other" anymore?

**Comment by arichiardi** [comment]
Can it be that it does not prepend because my package is local? Can we merge it and see if it still does it? How can I debug this?

**Comment by Deraen** [comment]
If by local package you mean that you have installed this to your local maven repo with `build-jar` there's no reason to try merging. There's no difference between local and clojars deps.

**Comment by arichiardi** [comment]
Of course, I am kind of desperate and I don't know how to debug this...

**Comment by arichiardi** [comment]
By the way my ```deps.cljs``` looks correct:

``` clojure

{:foreign-libs [{:file "cljsjs/jqconsole/development/jqconsole.inc.js", :provides ["cljsjs.jqconsole"],
                       :requires ["cljsjs.jquery"],
                      :file-min "cljsjs/jqconsole/production/jqconsole.min.inc.js"}], 
                      :externs ["cljsjs/jqconsole/common/jqconsole.ext.js"]}
```

I really can't understand what's failing.

**Comment by arichiardi** [comment]
BTW why ```packages/jquery``` does not have ```cljsjs/resources/jquery``` folder structure? Can it be a problem?

**Comment by Deraen** [comment]
Jquery was probably packaged before we had the convention about folder structure. Doesn't matter as long as deps.cljs files refer to proper paths.

**Comment by Deraen** [comment]
I did check with boot-cljs and minified jqconsole code was included in advanced build.

**Comment by martinklepsch** [comment]
My guess is that some of your other dependencies depended on an older version of clojurescript that might have had only partial support for `deps.cljs`. A repo with reproduction steps would help figuring that out.

**Comment by arichiardi** [comment]
Must be cljsbuild then, I tried with mies and it works too, I guess if you see $('#somediv).jqconsole("ttt", ..) we are good to merge

**Comment by arichiardi** [comment]
BTW I am always trying with ClojureScript 122.

**Comment by Deraen** [comment]
Is there a reason why CSS file is include in the repo and now downloaded?

**Comment by arichiardi** [comment]
Yes I think is part of the "standart formatting" one can use (for instance ANSI). It was like this and I kept it, I have never used it though

**Comment by Deraen** [comment]
Yeah but instead of including it in the repo, you could just sift it from the package to proper path like you are doing with the JS files.

**Comment by arichiardi** [comment]
Ah yes it's true, I guess it is better

**Comment by arichiardi** [comment]
Do you think I should include?

```
/**
 * @constructor
 * @param {(jQuerySelector|Element|Object|Array<Element>|jQuery|string|
 *     function())=} arg1
 * @param {(Element|jQuery|Document|
 *     Object<string, (string|function(!jQuery.Event))>)=} arg2
 * @return {!jQuery}
 */
var $ = function (arg1, arg2) {};
```

It should be in ```jquery``` already...

**Comment by arichiardi** [comment]
Ok this is ready, I removed all the unnecessary things, also speaking with @amasad and tested with ```:optimizations :advanced```

**Comment by martinklepsch** [comment]
It seems the error you encountered has been fixed in ClojureScript master: https://github.com/clojure/clojurescript/commit/a4d6a241cd9d45bf0356809c18df14585befd68f

**Comment by arichiardi** [comment]
:+1: let's merge :smile: and thanks for the support! It was such a weird bug.

**Comment by arichiardi** [comment]
I have noticed that there was some issue in the commit message, in the meantime I upgraded to jqconsole 2.12...about to push!

**Comment by arichiardi** [comment]
Ok now it should be good to go, I have tested it as well in a pet project of mine

**Comment by amasad** [comment]
yeah, I tagged the branch before doing the build. But then reverted it and
corrected

**Comment by arichiardi** [comment]
Here everything works fine, basically boot downloads from https://github.com/replit/jq-console/zipball/master

**Comment by arichiardi** [comment]
Can I ask for a little bump :) Can we merge this branch?

**Comment by martinklepsch** [comment]
@arichiardi hey :) instead of downloading the zip from master can we download from a tagged release artifact as they are listed on the release pages? (e.g. https://github.com/replit/jq-console/releases/tag/v2.13.1)

**Comment by arichiardi** [comment]
Ok will change it

**Comment by arichiardi** [comment]
Ok done, I checked it is working, tell me if I need to squash as well ok?

**Comment by martinklepsch** [comment]
@arichiardi Sorry this took so long. It's merged now and I just published to Clojars. :+1: 
```
[cljsjs/jqconsole "2.13.1-0"]
```

**Comment by arichiardi** [comment]
Awesome!

**Pull request closed without merging**
