### PR TITLE
First pass of paho lib.

### PR DESCRIPTION
**Pull request by thomas-shares**
Hi,

This is my first attempt at creating a pull request to CLJSJS, please review and comment and let me know what I can improve. 

Many thanks,
Thomas

### CODE REVIEW

**Comment by Deraen** [comment]
I just updated the wiki with notes about version vars: https://github.com/cljsjs/packages/wiki/Creating-Packages#51-buildboot

I think the methods and properties are declared are incorrectly in the extern. I think the correct way would be to declare them as prototype methods of client: `Paho.MQTT.Client.prototype.connect = function(connectionOptions) {};`

Some examples from React extern:
https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/react/common/react.ext.js#L111
https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/react/common/react.ext.js#L150

**Comment by Deraen** [comment]
@thomas-shares Hi, what's the status of this PR?

**Comment by thomas-shares** [comment]
Hi,

Could this pull request be merged now? Thank you.

Thomas

**Comment by Deraen** [comment]
Tests were still failing but I guess that's because this was based on such old commit. I'll see that this will get deployed.

**Pull request merged**
