### PR TITLE
[filestack] inital

### PR DESCRIPTION
**Pull request by martinklepsch**
This adds [Filestack](https://www.filestack.com/docs/).

Unfortunately they don't version their builds properly so I just used 0.0.1 as version & added a little note about the lack of versioning to the readme.

### CODE REVIEW

**Comment by Deraen** [comment]
If they presume users load the code from their cdn, perhaps this counts as a special case where only the extern should be packaged: https://github.com/cljsjs/packages/wiki/Extern-only-packages ?

**Comment by martinklepsch** [comment]
@Deraen I considered that but the md5 is always the same so I don't think they do any special on the flight packaging like e.g. Google Maps.

**Comment by Deraen** [comment]
What about these bower and npm packages mentioned on [Filestack docs](https://www.filestack.com/docs/)?

https://www.npmjs.com/package/filepicker-js
https://github.com/filepicker/filepicker-js-bower
https://github.com/filepicker/filepicker-js

filepicker.io seems to redirect to filestack.io.

**Comment by martinklepsch** [comment]
@Deraen uh, this looks good. I'll update the PR to get a versioned artifact from there. Still I'm not seeing why this should be an externs only package, do you?

**Comment by Deraen** [comment]
No reason if there is a proper versioned artifact.

If only a file from a vender cdn is available updates would be hard to manage. Even if the vendor doesn't do "on the flight packaging like Google Maps" they might update the file in two weeks or two months. Without versioning this is hard to notice and hard to communicate to library users.

**Comment by martinklepsch** [comment]
> Without versioning this is hard to notice and hard to communicate to library users.

Agreed, will update the package to use versioned artifacts. I'll recheck with Filestack if there are any other reasons why you should inline their js file.

**Comment by martinklepsch** [comment]
Heard back from Filestack, there's no reason to not inline it.

**Pull request merged**
