### PR TITLE
Update vega stuff

### PR DESCRIPTION
**Pull request by jsa-aerial**

### CODE REVIEW

**Comment by jsa-aerial** [comment]
@Deraen Hi, any chance of this getting pushed?  Does it make any sense to allow others write access?  Yes, I know that CLJSJS is somewhat deprecated, but I need this out while looking into migrating off CLJSJS

**Comment by jsa-aerial** [comment]
Many Thanks!  works fine!  Hmmm, doesn't look like I can close this

**Comment by jsa-aerial** [comment]
Ooops, sorry - i see it is already closed!

**Comment by Deraen** [comment]
@jsa-aerial I also sent you an invite to cljsjs org, so you can merge these yourself.

**Comment by jsa-aerial** [comment]
that's odd - I do not have any notification for that.  where would that show up?  How do I go about accepting it??

**Comment by jsa-aerial** [comment]
never mind - i see it now.  Showed up in an 'odd' folder.  Anyway, now a member!

**Pull request merged**
