### PR TITLE
[document-register-element] Added 0.2.1

### PR DESCRIPTION
**Pull request by jeluard**
Introduced the cljsjs package for [document-register-element](https://github.com/WebReflection/document-register-element).

### CODE REVIEW

**Comment by jeluard** [comment]
What do you guys think about this one? Can I go ahead and merge it?

**Comment by martinklepsch** [comment]
I think it'd be good to have a note in the read me why there are no
externs, other than that looks good :)

**Comment by jeluard** [comment]
Great!

**Comment by martinklepsch** [comment]
Awesome, thank you! :)

**Pull request merged**
