### PR TITLE
Upgrade react-datepicker

### PR DESCRIPTION
**Pull request by AshtonKem**
I'm getting errors on the old version, checking to see if a newer version fixes it.

### CODE REVIEW

**Comment by Deraen** [comment]
Thanks for the contribution, but I had to revert this. The package task is failing and I can't easily fix it because the zip file does not contain plain JS files anymore, only JSX files. Probably it would require running some NPM commands to run JSX/Browserify to build the plain file. Check e.g. forge package task for how to run Node during package: https://github.com/cljsjs/packages/blob/e7abebb298acc839ec0145c9ebf93a092bf2c6c6/forge/build.boot#L32

Please test changes locally in future before opening a PR.

**Comment by ducky427** [comment]
@AshtonKem, have a look at this issue Hacker0x01/react-datepicker#303. Seems like the repo doesn't have a dist folder anymore.

**Comment by ducky427** [comment]
@AshtonKem, generating `dist/react-datepicker.js` and `dist/react-datepicker.min.js` is relatively straightforward:

- `npm install`
- `grunt webpack`

The first command may complain if ruby and `scss-lint` aren't installed.

But generating the css file is more involved as it involves having ruby and [`scss-lint`](https://github.com/brigade/scss-lint) installed.

**Comment by AshtonKem** [comment]
I was under the impression that cljsjs packages don't expose css files for its users. If that's the case, does it matter if the case files aren't generated?

--
Ashton

**Comment by ducky427** [comment]
Currently `react-datepicker` does expose the css files for its users which can be used by `boot` but not using `lein`.

@Deraen whats the policy regarding css files?

**Comment by Deraen** [comment]
If the package has css files, it's good to expose them. Other packages should contain examples about this.

CI system has Ryby available so it should be possible to run a gem command before running grunt build, to install `scss-lint`.

There is no reason why Lein users could not make use of those css files, they just need either smart enough plugin (less4clj) or some middleware to serve them.

**Pull request merged**
