### PR TITLE
[leaflet-polylinedecorator] Add leaflet-polylinedecorator

### PR DESCRIPTION
**Pull request by transducer**
I put externs in leaflet externs because I don't know how to extend L (if it is possible at all).

It does work for my use case (adding leaflet + polylinedecorator) and using it.

### CODE REVIEW

**Comment by transducer** [comment]
Ah maybe I can extend `L` using:

```
L.PosAnimation = function () {};
L.Symbol.marker = function() {};
L.polylineDecorator = function() {};
```

**Comment by transducer** [comment]
I did that and changed the commit. It works.

**Comment by Deraen** [comment]
You should also add leaflet dependency and deps.cljs require to leaflet: https://github.com/cljsjs/packages/blob/master/leaflet-locatecontrol/build.boot

**Comment by transducer** [comment]
Done

**Pull request merged**
