### PR TITLE
[highlight] Updated to 10.3.1

### PR DESCRIPTION
**Pull request by 2knu**

### CODE REVIEW

**Comment by Deraen** [comment]
@2knu Seeing how many packages you are using, have you seen this: https://github.com/cljsjs/packages/issues/2127 ?

I also sent you an invite to the cljsjs org, so you can merge these updates yourself.

**Comment by 2knu** [comment]
@Deraen Oh thanks for invitation! 

Yes I see the issue, but I primary maintain the cljsjs packages for the company which I work for and push them to our private artefact repository. So I thought it might be helpful for others, when I push it here too :)
We use a lot of cljsjs packages in different projects and for us it's the easiest way for usage and maintenance to use cljsjs packages instead of npm. Also some lein plugins like ancient, deps, licences etc. dont work with npm dependencies.

**Comment by Deraen** [comment]
Yeah, makes sense.

As a note, npm of course has own set of tools which provide same features. But using two sets of tools is obviously inconvenient.

https://www.npmjs.com/package/npm-check-updates
https://github.com/dylang/npm-check
https://www.npmjs.com/package/license-checker

**Comment by 2knu** [comment]
Thanks for tooling hints, but as you said we want to use only one set of tooling.
Also we dont want to define and delivery the externs in every project and an extra project only for npm dependencies is a little bit superfluous. So what I want to say overall: cljsjs/packages is awesome, really helpful for us and upgrading packages is mostly very easy and requires only a small effort :)

**Comment by Deraen** [comment]
Externs aren't used at all with Shadow-cljs or Cljs+Webpack. I guess I could add mention about that to the draft.

**Pull request merged**
