### PR TITLE
[update] Firebase 3.0.*

### PR DESCRIPTION
**Pull request by flyboarder**
Update to Firebase 3.0.0

* Needs externs
* Newer version available from CDN (3.0.2)

Should we get CDN versions instead?

### CODE REVIEW

**Comment by flyboarder** [comment]
Relates to:

https://github.com/crisptrutski/matchbox/issues/74

**Comment by Deraen** [comment]
How has the extern been created? It looks quite quite small compared to Firebase API: https://firebase.google.com/docs/reference/js/#firebase.User

**Comment by martinklepsch** [comment]
I opened a ticket with firebase to ask if they could provide externs
directly. Will update here when I hear back.

I think the externs aren't done as they are in the PR, as Matthew
mentioned.

**Comment by Deraen** [comment]
Btw, if you need a release without externs for dev, I think we can do a release with alpha indetifier?

```clj
(def +version+ (str +lib-version+ "-alpha0"))
```

**Comment by amitburst** [comment]
It looks like the Firebase npm package provides externs now.

**Comment by flyboarder** [comment]
@Deraen ready 👍

**Comment by flyboarder** [comment]
@amitburst thanks for the heads up! 😸

**Pull request merged**
